//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakerLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FakerLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Беларусь, г. Мiнск
        ///Беларусь, г. Гродна
        ///Беларусь, г. Вiцебска
        ///Беларусь, г. Брэст
        ///Беларусь, г. Магiлев
        ///Беларусь, г. Гомель
        ///Беларусь, Мiнская обласць
        ///Беларусь, Гродзенская обласць
        ///Беларусь, Брэсцкая обласць
        ///Беларусь, Вiцебская обласць
        ///Беларусь, Магiлеўская обласць
        ///Беларусь, Гомельская обласць
        ///Беларусь, г. Арабаўшчына
        ///Беларусь, г. Болтичи
        ///Беларусь, г. Бриксичи
        ///Беларусь, г. Вялікае Сяло
        ///Беларусь, г. Гарановіч
        ///Беларусь, г. Грыбаўшчына
        ///Беларусь, г. Душковцы
        ///Беларусь, г. Зялёная
        ///Беларусь, г. Кіс [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_City {
            get {
                return ResourceManager.GetString("BY_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алiмпiяда
        ///Алiса
        ///Алiна
        ///Алеся
        ///Алена 
        ///Алаiза
        ///Ала
        ///Аксiння
        ///Акiлiна
        ///Адэля
        ///Адэлаiда 
        ///Ада 
        ///Агрыпiна
        ///Аглаiда
        ///Агата
        ///Бранiслава
        ///Бранiслава
        ///Барбара
        ///Баляслава
        ///Багуслава
        ///Багдана
        ///Вульяна
        ///Вольга
        ///Вiялета
        ///Вiктарына
        ///Вiкторыя
        ///Веранiка
        ///Вера
        ///Васiлiса
        ///Васiлiна
        ///Варвара
        ///Валянцiна
        ///Валерыя
        ///Глафiра
        ///Гелена 
        ///Ганна
        ///Галiна
        ///Еўфрасiння
        ///Еўпраксiя
        ///Еўдакiя
        ///Елiзавета
        ///Ева
        ///Дарафея
        ///Данута
        ///Дамiнiка
        ///Iрына
        ///Iона
        ///Iна
        ///Зоя
        ///Зiновiя
        ///Зiнаiда
        ///Жана
        ///Ксенiя
        ///Клаўдзiя
        ///Клара
        ///Кiра
        ///Кацярына
        ///Каралiна
        ///Камiла
        ///К [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Female_Names {
            get {
                return ResourceManager.GetString("BY_Female_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Леанiдаўна
        ///Борiславовна
        ///Глебавiчна
        ///Гаўрылаўна
        ///Еўдакiмаўна
        ///Аркадiевна
        ///Ульяновна
        ///Уладзiмiраўна
        ///Сократовна
        ///Артеiменовна
        ///Мстiславовна
        ///Янаўна
        ///Андрэеўна
        ///Рубеновна
        ///Фёдараўна
        ///Грiгоргiевна
        ///Елiзаровна
        ///Арiстарховна
        ///Уладзiславаўна
        ///Радiоновна
        ///Мiкалаеўна
        ///Мiхаiловна
        ///Владiленовна
        ///Сiдараўна
        ///Самуiловна
        ///Серафiмаўна
        ///Сiгiзмундовна
        ///Анатолiевна
        ///Терентьевна
        ///Пахомовна
        ///Генадзьеўну
        ///Германаўна
        ///Расцiславаўна
        ///Русланаўна
        ///iванаўна
        ///Антiповна
        ///Клавдiевна
        ///Пiлiпаўна
        ///Дзмiтрыеўна
        ///Остаповна
        ///Венедiктовна
        ///Ма [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Female_Patr {
            get {
                return ResourceManager.GetString("BY_Female_Patr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Негiна
        ///Зiнчанка
        ///Судлянкова
        ///Яўлiнскi
        ///Губiна
        ///Мiлюкова
        ///Ручкiна
        ///Кардапольцева
        ///Потрепалова
        ///Набалкiна
        ///Карчагiна
        ///Бальшова
        ///Ярлыкова
        ///Клiнскага
        ///Дзюкаў
        ///Маслюк
        ///Нiкешiна
        ///Кузiкаў
        ///Вахрушава
        ///Гнусарава
        ///Дутаў
        ///Лассмана
        ///Кулiка
        ///Уткiна
        ///Бармыкiна
        ///Хлебова
        ///Раманава
        ///Нiзьева
        ///Кузьмiн
        ///Нагiбiна
        ///Прахiна
        ///Ханцева
        ///Канадiна
        ///Гаврюшiна
        ///Копорiкова
        ///Толоконская
        ///Дьячкова
        ///Чаркасава
        ///Арлова
        ///Кампанец
        ///Бажко
        ///Яхiмовiч
        ///Ясенева
        ///Сiякаева
        ///Лескова
        ///Досаева
        ///Ясюлевiч
        ///Нiкулiна
        ///Цiханенка
        ///Галiцкова
        ///Ретюнскiха
        ///Алекс [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Female_Surnames {
            get {
                return ResourceManager.GetString("BY_Female_Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрыян
        ///Азар
        ///Алег
        ///Алесь
        ///Алiзар
        ///Альберт
        ///Аляксандр
        ///Аляксей
        ///Анатоль
        ///Андрэй
        ///Антон
        ///Аркадзь
        ///Артур
        ///Арцём
        ///Багдан 
        ///Барыс
        ///Банiфацый
        ///Бенедыкт
        ///Вадзiм
        ///Валерый
        ///Валянцiн
        ///Ванiфат
        ///Варлам
        ///Васiль
        ///Венiямiн
        ///Вiктар 
        ///Вiнцэнт
        ///Вiталь
        ///Вiтаўт
        ///Вячаслаў
        ///Гарасiм
        ///Гардзей
        ///Генадзь 
        ///Генрык
        ///Георгiй
        ///Геранiм
        ///Герман
        ///Глеб
        ///Грыгор
        ///Давыд
        ///Далмат
        ///Дамiнiк
        ///Дарафей
        ///Дзмiтрый
        ///Дзямiд
        ///Дзянiс
        ///Езекiiль
        ///Елiзар
        ///Емяльян
        ///Ерамей
        ///Еранiм
        ///Ерафей
        ///Еўдакiм
        ///Засiм
        ///Захар
        ///Зыгмунт
        ///Iван
        ///Iгар
        ///Iгнат
        ///Iзяслаў 
        ///Iлья
        ///Iпалi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Male_Names {
            get {
                return ResourceManager.GetString("BY_Male_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iзмаiловiч
        ///Дмiтрiевiч
        ///Ерофеевiч
        ///Кондратовiч
        ///Евстафiевiч
        ///Несторовiч
        ///Онiсiмовiч
        ///Серафiмовiч
        ///Грiгорiевiч
        ///Iгнатiевiч
        ///Iзяславовiч
        ///Богдановiч
        ///Мартьяновiч
        ///Евгенiевiч
        ///Пахомовiч
        ///Родiоновiч
        ///Мечiславовiч
        ///Прохоровiч
        ///Георгiевiч
        ///Леоновiч
        ///Валерiевiч
        ///Феоктiстовiч
        ///Сергеевiч
        ///Адамовiч
        ///Нiкiфоровiч
        ///Зiновiевiч
        ///Эрнстовiч
        ///Всеволодовiч
        ///Арсенiевiч
        ///Iвановiч
        ///Онуфрiевiч
        ///Купрiяновiч
        ///Захаровiч
        ///Ефремовiч
        ///Гаврiлевiч
        ///Леонтiевiч
        ///Фомевiч
        ///Геннадiевiч
        ///Эрнестовiч
        ///Ростiславовiч
        ///Матвеевiч
        ///Андроновiч
        ///Ермола [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Male_Patr {
            get {
                return ResourceManager.GetString("BY_Male_Patr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмкiн
        ///Убыш
        ///Мармазоу
        ///Авдошкiн
        ///Ельченко
        ///Карандасоу
        ///Саяноуiч
        ///Мiнаев
        ///Будаев
        ///Ярiлоу
        ///Староуолкоу
        ///Грехоу
        ///Iльiнскiй
        ///Ермакоу
        ///Рогоу
        ///Петракоу
        ///Шашкоу
        ///Лёвкiн
        ///Сiдороу
        ///Ласман
        ///Кабiсоу
        ///Чупроу
        ///Штельмах
        ///Iсаев
        ///Крiвонос
        ///Зефiроу
        ///Касатый
        ///Булка
        ///Шiшмарёв
        ///Жжёноу
        ///Янiшiн
        ///Яламоу
        ///Трошкiн
        ///Лобза
        ///Дуболазоу
        ///Iгнатенко
        ///Лебедiнскiй
        ///Пода
        ///Коптiльнiкоу
        ///Рязанцев
        ///Хорошавцев
        ///Комзiн
        ///Зыряноу
        ///Крумiньш
        ///Смолiн
        ///Бобр
        ///Крiворотоу
        ///Чекудаев
        ///Сафоноу
        ///Слатiн
        ///Ушакоу
        ///Капшукоу
        ///Скороходоу
        ///Яшенкiн
        ///Стрекалоу
        ///Кондр [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Male_Surnames {
            get {
                return ResourceManager.GetString("BY_Male_Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вул. Абрыкосавая в.
        ///вул. Авакяна в.
        ///вул. Авангардная в.
        ///зав. Авангардны в.
        ///вул. Авіяцыі в.
        ///вул. Авроровская в.
        ///вул. Автодоровская в.
        ///зав. Автодоровскiй в.
        ///вул. Аўтазаводская в.
        ///зав. Аўтазаводскі в.
        ///вул. Аўтамабілістаў в.
        ///зав. Агатавых в.
        ///вул. Адама Шэмэша в.
        ///вул. Азгура в.
        ///вул. Азізавым в.
        ///вул. Азоўская в.
        ///зав. Айвазоўскага в.
        ///вул. Айвазоўскага в.
        ///вул. Акадэміка Высоцкага в.
        ///зав. Акадэміка Вышалескага в.
        ///вул. Акадэміка Вышалескага в.
        ///зав. Акадэміка Жэбрака в.
        ///вул. Акадэміка Жэбрака в.        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BY_Street {
            get {
                return ResourceManager.GetString("BY_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bath
        ///Birmingham
        ///Bolton
        ///Brighton
        ///Bristol
        ///Bradford
        ///Windsor
        ///Wolverhampton
        ///Gloucester
        ///Derby
        ///Dover
        ///Ipswich
        ///York
        ///Cambridge
        ///Canterbury
        ///Coventry
        ///Colchester
        ///Crosby
        ///Kingston-upon-Hull
        ///Liverpool
        ///Leeds
        ///Lester
        ///London
        ///Luton
        ///Manchester
        ///Nottingham
        ///Norwich
        ///Newcastle-upon-Tyne
        ///Oxford
        ///Peterborough
        ///Plymouth
        ///Portsmouth
        ///Preston
        ///Reading
        ///Sunderland
        ///Southampton
        ///Swindon
        ///Salisbury
        ///Stoke-on-Trent
        ///Cheltenham
        ///York
        ///Chester
        ///Sheffield
        ///Exter
        ///Cardiff
        ///Newport
        ///Swansea
        ///Monmouth
        ///Wrexham
        ///Antrim
        ///Ba [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_City {
            get {
                return ResourceManager.GetString("EN_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mary
        ///Patricia
        ///Linda
        ///Barbara
        ///Elizabeth
        ///Jennifer
        ///Maria
        ///Susan
        ///Margaret
        ///Dorothy
        ///Lisa
        ///Nancy
        ///Karen
        ///Betty
        ///Helen
        ///Sandra
        ///Donna
        ///Carol
        ///Ruth
        ///Sharon
        ///Michelle
        ///Laura
        ///Sarah
        ///Kimberly
        ///Deborah
        ///Jessica
        ///Shirley
        ///Cynthia
        ///Angela
        ///Melissa
        ///Brenda
        ///Amy
        ///Anna
        ///Rebecca
        ///Virginia
        ///Kathleen
        ///Pamela
        ///Martha
        ///Debra
        ///Amanda
        ///Stephanie
        ///Carolyn
        ///Christine
        ///Marie
        ///Janet
        ///Catherine
        ///Frances
        ///Ann
        ///Joyce
        ///Diane
        ///Alice
        ///Julie
        ///Heather
        ///Teresa
        ///Doris
        ///Gloria
        ///Evelyn
        ///Jean
        ///Cheryl
        ///Mildred
        ///Katherine
        ///Joan
        ///Ashley
        ///Judi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_Female_Names {
            get {
                return ResourceManager.GetString("EN_Female_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на James
        ///John
        ///Robert
        ///Michael
        ///William
        ///David
        ///Richard
        ///Charles
        ///Joseph
        ///Thomas
        ///Christopher
        ///Daniel
        ///Paul
        ///Mark
        ///Donald
        ///George
        ///Kenneth
        ///Steven
        ///Edward
        ///Brian
        ///Ronald
        ///Anthony
        ///Kevin
        ///Jason
        ///Matthew
        ///Gary
        ///Timothy
        ///Jose
        ///Larry
        ///Jeffrey
        ///Frank
        ///Scott
        ///Eric
        ///Stephen
        ///Andrew
        ///Raymond
        ///Gregory
        ///Joshua
        ///Jerry
        ///Dennis
        ///Walter
        ///Patrick
        ///Peter
        ///Harold
        ///Douglas
        ///Henry
        ///Carl
        ///Arthur
        ///Ryan
        ///Roger
        ///Joe
        ///Juan
        ///Jack
        ///Albert
        ///Jonathan
        ///Justin
        ///Terry
        ///Gerald
        ///Keith
        ///Samuel
        ///Willie
        ///Ralph
        ///Lawrence
        ///Nicholas
        ///Roy
        ///Benjamin [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_Male_Names {
            get {
                return ResourceManager.GetString("EN_Male_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Baker street
        ///Bond Street
        ///Downing street
        ///Carnaby Street
        ///Regent Street
        ///Oxford street
        ///Piccadilly street
        ///Whitehall Street
        ///Fleet Street
        ///Abbey Road.
        /// </summary>
        internal static string EN_Street {
            get {
                return ResourceManager.GetString("EN_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smith
        ///Johnson
        ///Williams
        ///Jones
        ///Brown
        ///Davis
        ///Miller
        ///Wilson
        ///Moore
        ///Taylor
        ///Anderson
        ///Thomas
        ///Jackson
        ///White
        ///Harris
        ///Martin
        ///Thompson
        ///Garcia
        ///Martinez
        ///Robinson
        ///Clark
        ///Rodriguez
        ///Lewis
        ///Lee
        ///Walker
        ///Hall
        ///Allen
        ///Young
        ///Hernandez
        ///King
        ///Wright
        ///Lopez
        ///Hill
        ///Scott
        ///Green
        ///Adams
        ///Baker
        ///Gonzalez
        ///Nelson
        ///Carter
        ///Mitchell
        ///Perez
        ///Roberts
        ///Turner
        ///Phillips
        ///Campbell
        ///Parker
        ///Evans
        ///Edwards
        ///Collins
        ///Stewart
        ///Sanchez
        ///Morris
        ///Rogers
        ///Reed
        ///Cook
        ///Morgan
        ///Bell
        ///Murphy
        ///Bailey
        ///Rivera
        ///Cooper
        ///Richardson
        ///Cox
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EN_Surnames {
            get {
                return ResourceManager.GetString("EN_Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия, г. Абалак (Тюменская область)
        ///Россия, г. Абдаево (Республика Марий-Эл)
        ///Россия, г. Абрамцево (Московская область)
        ///Россия, г. Авдотьино (Московская область)
        ///Россия, г. Авдотьино (Московская область)
        ///Россия, г. Адлер (Краснодарский край)
        ///Россия, г. Азов (Ростовская область)
        ///Россия, г. Акатово (Московская область)
        ///Россия, г. Аксай (Ростовская область)
        ///Россия, г. Акташ (Республика Алтай)
        ///Россия, г. Акулова Гора (Ленинградская область)
        ///Россия, г. Алакаевка (Самарская область)
        ///Россия, г. Алапае [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_City {
            get {
                return ResourceManager.GetString("RUS_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Августа
        ///Августина
        ///Авдотья
        ///Аврелия
        ///Аврея
        ///Аврора
        ///Агапа
        ///Агапия
        ///Агарь
        ///Агита
        ///Агафа
        ///Агафоклия
        ///Агафоника
        ///Агафья
        ///Агафия
        ///Аглаида
        ///Аглая
        ///Агна
        ///Агнесса
        ///Агния
        ///Аграфена
        ///Агриппина
        ///Ада
        ///Аделаида
        ///Аделина
        ///Аделла
        ///Адель
        ///Адельфина
        ///Адина
        ///Адолия
        ///Адриана
        ///Аза
        ///Азалия
        ///Азелла
        ///Аида
        ///Акилина
        ///Аксинья
        ///Аксиния
        ///Акулина
        ///Алевтина
        ///Александра
        ///Александрина
        ///Алексина
        ///Алёна
        ///Алина
        ///Алиса
        ///Алла
        ///Алфея
        ///Альберта
        ///Альбертина
        ///Альбина
        ///Альвина
        ///Альфия
        ///Амалия
        ///Амата
        ///Амелфа
        ///Анастасия
        ///Анатолия
        ///Ангела
        ///Ангелика        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Female_Names {
            get {
                return ResourceManager.GetString("RUS_Female_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Леонидовна
        ///Бориславовна
        ///Глебовна
        ///Гавриловна
        ///Евдокимовна
        ///Аркадиевна
        ///Ульяновна
        ///Владимировна
        ///Сократовна
        ///Артеименовна
        ///Мстиславовна
        ///Яновна
        ///Андреевна
        ///Рубеновна
        ///Федоровна
        ///Григоргиевна
        ///Елизаровна
        ///Аристарховна
        ///Владиславовна
        ///Радионовна
        ///Николаевна
        ///Михаиловна
        ///Владиленовна
        ///Сидоровна
        ///Самуиловна
        ///Серафимовна
        ///Сигизмундовна
        ///Анатолиевна
        ///Терентьевна
        ///Пахомовна
        ///Геннадиевна
        ///Германовна
        ///Ростиславовна
        ///Руслановна
        ///Ивановна
        ///Антиповна
        ///Клавдиевна
        ///Филипповна
        ///Дмитриевна
        ///Остаповна
        ///Венедиктовна
        ///Макаро [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Female_Patr {
            get {
                return ResourceManager.GetString("RUS_Female_Patr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Негина
        ///Зинченко
        ///Судленкова
        ///Явлинская
        ///Губина
        ///Милюкова
        ///Ручкина
        ///Кардапольцева
        ///Потрепалова
        ///Набалкина
        ///Карчагина
        ///Большова
        ///Ярлыкова
        ///Клинских
        ///Дюкова
        ///Маслюк
        ///Никешина
        ///Кузик
        ///Вахрушева
        ///Гнусарева
        ///Дутова
        ///Лассмана
        ///Кулика
        ///Уткина
        ///Бармыкина
        ///Хлебова
        ///Романова
        ///Низьева
        ///Кузьминых
        ///Нагибина
        ///Пряхина
        ///Ханцева
        ///Канадина
        ///Гаврюшина
        ///Копорикова
        ///Толоконская
        ///Дьячкова
        ///Черкасова
        ///Орлова
        ///Компанец
        ///Божко
        ///Яхимович
        ///Ясенева
        ///Сиякаева
        ///Лескова
        ///Досаева
        ///Ясюлевич
        ///Никулина
        ///Тихоненко
        ///Галицкова
        ///Ретюнскиха
        ///Алек [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Female_Surnames {
            get {
                return ResourceManager.GetString("RUS_Female_Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абакум
        ///Абрам
        ///Абросим
        ///Аввакум
        ///Август
        ///Авдей
        ///Авдий
        ///Авель
        ///Авенир
        ///Аверий
        ///Аверкий
        ///Аверьян
        ///Авксентий
        ///Аврам
        ///Аврелиан
        ///Автоном
        ///Агап
        ///Агапий
        ///Агапит
        ///Агафангел
        ///Агафон
        ///Аггей
        ///Адам
        ///Адриан
        ///Азар
        ///Азарий
        ///Акакий
        ///Акила
        ///Аким
        ///Акиндин
        ///Акинф
        ///Акинфий
        ///Аксён
        ///Аксентий
        ///Александр
        ///Алексей
        ///Алексий
        ///Альберт
        ///Альфред
        ///Амвросий
        ///Амос
        ///Амфилохий
        ///Ананий
        ///Анастасий
        ///Анатолий
        ///Андрей
        ///Андриан
        ///Андрон
        ///Андроний
        ///Андроник
        ///Анект
        ///Анемподист
        ///Аникей
        ///Аникий
        ///Аникита
        ///Анисий
        ///Анисим
        ///Антиох
        ///Антип
        ///Антипа
        ///Антипий
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Male_Names {
            get {
                return ResourceManager.GetString("RUS_Male_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измаилович
        ///Дмитриевич
        ///Ерофеевич
        ///Кондратович
        ///Евстафиевич
        ///Несторович
        ///Онисимович
        ///Серафимович
        ///Григориевич
        ///Игнатиевич
        ///Изяславович
        ///Богданович
        ///Мартьянович
        ///Евгениевич
        ///Пахомович
        ///Родионович
        ///Мечиславович
        ///Прохорович
        ///Георгиевич
        ///Леонович
        ///Валериевич
        ///Феоктистович
        ///Сергеевич
        ///Адамович
        ///Никифорович
        ///Зиновиевич
        ///Эрнстович
        ///Всеволодович
        ///Арсениевич
        ///Иванович
        ///Онуфриевич
        ///Куприянович
        ///Захарович
        ///Ефремович
        ///Гаврилевич
        ///Леонтиевич
        ///Фомевич
        ///Геннадиевич
        ///Эрнестович
        ///Ростиславович
        ///Матвеевич
        ///Андронович
        ///Ермола [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Male_Patr {
            get {
                return ResourceManager.GetString("RUS_Male_Patr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмкин
        ///Убыш
        ///Мармазов
        ///Авдошкин
        ///Ельченко
        ///Карандасов
        ///Саянович
        ///Минаев
        ///Будаев
        ///Ярилов
        ///Староволков
        ///Грехов
        ///Ильинский
        ///Ермаков
        ///Рогов
        ///Петраков
        ///Шашков
        ///Лёвкин
        ///Сидоров
        ///Ласман
        ///Кабисов
        ///Чупров
        ///Штельмах
        ///Исаев
        ///Кривонос
        ///Зефиров
        ///Касатый
        ///Булка
        ///Шишмарёв
        ///Жжёнов
        ///Янишин
        ///Яламов
        ///Трошкин
        ///Лобза
        ///Дуболазов
        ///Игнатенко
        ///Лебединский
        ///Пода
        ///Коптильников
        ///Рязанцев
        ///Хорошавцев
        ///Комзин
        ///Зырянов
        ///Круминьш
        ///Смолин
        ///Бобр
        ///Криворотов
        ///Чекудаев
        ///Сафонов
        ///Слатин
        ///Ушаков
        ///Капшуков
        ///Скороходов
        ///Яшенкин
        ///Стрекалов
        ///Кондр [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Male_Surnames {
            get {
                return ResourceManager.GetString("RUS_Male_Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 19 партсъезда п д.
        ///19 партсъезда п д.
        ///4-й участок п д.
        ///40 Домиков п д.
        ///40 лет Октября снт д.
        ///5-й участок п д.
        ///Авангард снт д.
        ///Авиагородок п д.
        ///Авиатор снт д.
        ///Алюминиевый пгт д.
        ///Ангарский п д.
        ///Архитектор снт д.
        ///Аэропорт п д.
        ///Бекетовская п/ст д.
        ///Бекетовская ст д.
        ///Бекетовский перевал х д.
        ///Бекетовский перекат х д.
        ///Берендей снт д.
        ///Бетонщик снт д.
        ///Бирюзовая ст д.
        ///Бобыли х д.
        ///Бобыли п д.
        ///ВПЭЛС п д.
        ///Верхнезареченский пгт д.
        ///Веселая Балка п д.
        ///Веселая Балка п д.
        ///Ветеран снт д.
        ///Вишневая ст  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RUS_Street {
            get {
                return ResourceManager.GetString("RUS_Street", resourceCulture);
            }
        }
    }
}
